n = int(input('Coloque um número: '))
print()
print('=' * 20)
print('|  1 x {} = {}       |'.format(n, n))
print('|  2 x {} = {}      |'.format(n, n * 2))
print('|  3 x {} = {}      |'.format(n, n * 3))
print('|  4 x {} = {}      |'.format(n, n * 4))
print('|  5 x {} = {}      |'.format(n, n * 5))
print('|  6 x {} = {}      |'.format(n, n * 6))
print('|  7 x {} = {}      |'.format(n, n * 7))
print('|  8 x {} = {}      |'.format(n, n * 8))
print('|  9 x {} = {}      |'.format(n, n * 9))
print('|  10 x {} = {}     |'.format(n, n * 10))
print('=' * 20)
