var = str(input("Coloque Seu Nome: "))
print("O seu nome em letras maiusculas: ", var.upper())
print("O seu nome em letras minusculas: ", var.lower())
print("O seu nome Com as 1º letras maiusculas: {}".format(var.title()))
x = var.count(' ')
z = len(var)
print("O número de letras do seu nome", z - x)
n = var.split()
print("O seu 1º nome é", n[0], "O número de letras do seu 1º nome:", len(n[0]))